# Generated by Django 4.2.3 on 2023-07-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='name',
            field=models.CharField(db_column='LINK', max_length=200),
        ),
    ]
