# Generated by Django 4.2.3 on 2023-07-10 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QPApp', '0003_rename_yourmodel_qpmodel_alter_qpmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qpmodel',
            table=None,
        ),
    ]
