# Generated by Django 4.2.3 on 2023-07-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QPApp', '0004_alter_qpmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qpmodel',
            table='PDF_LINKS',
        ),
    ]
